name: infologistix CD

on:
  push:
    branches:
    - main

jobs:
  debian:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Files
          uses: actions/checkout@v2
        - name: Setup BuildKit
          uses: docker/setup-buildx-action@v1
          id: buildx-debian
        - name: output
          run: echo ${{ steps.buildx-debian.outputs.platforms }}
        