name: infologistix CD

on:
  push:
    branches:
    - main
  schedule:
    - cron: "0 0 */7 * *"
  workflow_dispatch:
  

jobs:
  debian:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'infologistix/docker-selenium-python' }}
    steps:
        - name: Checkout Files
          uses: actions/checkout@v4
        - name: Setup QEMU
          uses: docker/setup-qemu-action@v3
          id: qemu-debian
          with:
            platforms: linux/arm/v7,linux/arm64,linux/amd64
        - name: Setup BuildKit
          uses: docker/setup-buildx-action@v3
          id: buildx-debian
        - name: Dockerhub login
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and Push Images
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ${{ github.repository }}:latest,${{ github.repository }}:bullseye,${{ github.repository }}:3.10-bullseye,${{ github.repository }}:3.10
            context: .
            file: Dockerfile-buster
            platforms: linux/arm64,linux/amd64
        - name: Update Docker Description
          uses: peter-evans/dockerhub-description@v2
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            repository: ${{ github.repository }}
            short-description: ${{ github.event.repository.description }}
  alpine:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'infologistix/docker-selenium-python' }}
    steps:
        - name: Checkout Files
          uses: actions/checkout@v4
        - name: Setup QEMU
          uses: docker/setup-qemu-action@v3
          id: qemu-alpine
          with:
            platforms: linux/arm/v7,linux/arm64,linux/amd64
        - name: Setup BuildKit
          uses: docker/setup-buildx-action@v3
          id: buildx-alpine
        - name: Dockerhub login
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and Push Images
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ${{ github.repository }}:alpine,${{ github.repository }}:3.10-alpine
            context: .
            file: Dockerfile-alpine
            platforms: linux/arm64,linux/amd64
        - name: Update Docker Description
          uses: peter-evans/dockerhub-description@v2
          with:
            username: ${{ secrets.DOCKERHUB_USER }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            repository: ${{ github.repository }}
            short-description: ${{ github.event.repository.description }}
            
